[package]
name = "netpulse-tui"
version = "0.1.0"
edition = "2021"
authors = ["Ali Joder <alijoder@gmail.com>"]
description = "Ultra-lightweight, zero-flicker, non-blocking terminal network dashboard in Rust"
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/unknownman/netpulse"
homepage = "https://github.com/unknownman/netpulse"
documentation = "https://docs.rs/netpulse-tui"
keywords = ["network", "tui", "monitoring", "bandwidth", "latency"]
categories = ["command-line-utilities", "network-programming"]

[[bin]]
name = "netpulse"
path = "src/main.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
futures = "0.3"
ratatui = "0.28"
crossterm = { version = "0.28", features = ["event-stream"] }
clap = { version = "4", features = ["derive"] }
sysinfo = "0.31"
surge-ping = "0.8"
socket2 = "0.5"
netstat2 = "0.11"
hickory-resolver = { version = "0.24", features = ["tokio-runtime"] }
clap_complete = "4"
anyhow = "1"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
